# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

try:  # patched
    from . import endpoints_pb2 as warden_dot_endpoints_dot_v1_dot_endpoints__pb2  # patched
    from .endpoints_pb2 import *  # patched
except ImportError:  # patched
    from ozbalance.warden.stubs.warden.endpoints.v1 import endpoints_pb2 as warden_dot_endpoints_dot_v1_dot_endpoints__pb2  # patched
    from ozbalance.warden.stubs.warden.endpoints.v1.endpoints_pb2 import *  # patched


class EndpointsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEndpoints = channel.unary_unary(
                '/endpoints.v1.EndpointsService/GetEndpoints',
                request_serializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetEndpointsRequest.SerializeToString,
                response_deserializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetEndpointsResponse.FromString,
                )
        self.WatchEndpoints = channel.unary_stream(
                '/endpoints.v1.EndpointsService/WatchEndpoints',
                request_serializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchEndpointsRequest.SerializeToString,
                response_deserializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchEndpointsResponse.FromString,
                )
        self.GetMSSQLEndpoints = channel.unary_unary(
                '/endpoints.v1.EndpointsService/GetMSSQLEndpoints',
                request_serializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetMSSQLEndpointsRequest.SerializeToString,
                response_deserializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetMSSQLEndpointsResponse.FromString,
                )
        self.WatchMSSQLEndpoints = channel.unary_stream(
                '/endpoints.v1.EndpointsService/WatchMSSQLEndpoints',
                request_serializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchMSSQLEndpointsRequest.SerializeToString,
                response_deserializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchMSSQLEndpointsResponse.FromString,
                )


class EndpointsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEndpoints(self, request, context):
        """GetEndpoints once returns Endpoints for the service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEndpoints(self, request, context):
        """WatchEndpoints creates subscription for service's endpoints.
        Service send updates immediately after getting notifications from k8s.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMSSQLEndpoints(self, request, context):
        """GetMSSQLEndpoints once returns MSSql Endpoints for the cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchMSSQLEndpoints(self, request, context):
        """WatchMSSQLEndpoints creates subscription for MSSql endpoints.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EndpointsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEndpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEndpoints,
                    request_deserializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetEndpointsRequest.FromString,
                    response_serializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetEndpointsResponse.SerializeToString,
            ),
            'WatchEndpoints': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEndpoints,
                    request_deserializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchEndpointsRequest.FromString,
                    response_serializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchEndpointsResponse.SerializeToString,
            ),
            'GetMSSQLEndpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMSSQLEndpoints,
                    request_deserializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetMSSQLEndpointsRequest.FromString,
                    response_serializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetMSSQLEndpointsResponse.SerializeToString,
            ),
            'WatchMSSQLEndpoints': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchMSSQLEndpoints,
                    request_deserializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchMSSQLEndpointsRequest.FromString,
                    response_serializer=warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchMSSQLEndpointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'endpoints.v1.EndpointsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EndpointsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEndpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.v1.EndpointsService/GetEndpoints',
            warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetEndpointsRequest.SerializeToString,
            warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetEndpointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchEndpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/endpoints.v1.EndpointsService/WatchEndpoints',
            warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchEndpointsRequest.SerializeToString,
            warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchEndpointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMSSQLEndpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.v1.EndpointsService/GetMSSQLEndpoints',
            warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetMSSQLEndpointsRequest.SerializeToString,
            warden_dot_endpoints_dot_v1_dot_endpoints__pb2.GetMSSQLEndpointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchMSSQLEndpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/endpoints.v1.EndpointsService/WatchMSSQLEndpoints',
            warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchMSSQLEndpointsRequest.SerializeToString,
            warden_dot_endpoints_dot_v1_dot_endpoints__pb2.WatchMSSQLEndpointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
