# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ozbalance.warden.stubs.warden.endpoints.v2 import endpoints_pb2 as platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2


class DiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Application = channel.unary_stream(
                '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/Application',
                request_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ApplicationRequest.SerializeToString,
                response_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ApplicationResponse.FromString,
                )
        self.ResourcePostgres = channel.unary_stream(
                '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourcePostgres',
                request_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresRequest.SerializeToString,
                response_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresResponse.FromString,
                )
        self.ResourceMSSQL = channel.unary_stream(
                '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourceMSSQL',
                request_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceMSSQLRequest.SerializeToString,
                response_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceMSSQLResponse.FromString,
                )
        self.ResourcePostgresSharded = channel.unary_stream(
                '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourcePostgresSharded',
                request_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedRequest.SerializeToString,
                response_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedResponse.FromString,
                )
        self.ResourcePostgresShardedV2 = channel.unary_stream(
                '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourcePostgresShardedV2',
                request_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedRequestV2.SerializeToString,
                response_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedResponseV2.FromString,
                )
        self.ResourceRedisSharded = channel.unary_stream(
                '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourceRedisSharded',
                request_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceRedisShardedRequest.SerializeToString,
                response_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceRedisShardedResponse.FromString,
                )
        self.ResourceKafka = channel.unary_unary(
                '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourceKafka',
                request_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceKafkaRequest.SerializeToString,
                response_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceKafkaResponse.FromString,
                )
        self.ResourceEtcd = channel.unary_unary(
                '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourceEtcd',
                request_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceEtcdRequest.SerializeToString,
                response_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceEtcdResponse.FromString,
                )


class DiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Application(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourcePostgres(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourceMSSQL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourcePostgresSharded(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourcePostgresShardedV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourceRedisSharded(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourceKafka(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourceEtcd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Application': grpc.unary_stream_rpc_method_handler(
                    servicer.Application,
                    request_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ApplicationRequest.FromString,
                    response_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ApplicationResponse.SerializeToString,
            ),
            'ResourcePostgres': grpc.unary_stream_rpc_method_handler(
                    servicer.ResourcePostgres,
                    request_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresRequest.FromString,
                    response_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresResponse.SerializeToString,
            ),
            'ResourceMSSQL': grpc.unary_stream_rpc_method_handler(
                    servicer.ResourceMSSQL,
                    request_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceMSSQLRequest.FromString,
                    response_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceMSSQLResponse.SerializeToString,
            ),
            'ResourcePostgresSharded': grpc.unary_stream_rpc_method_handler(
                    servicer.ResourcePostgresSharded,
                    request_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedRequest.FromString,
                    response_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedResponse.SerializeToString,
            ),
            'ResourcePostgresShardedV2': grpc.unary_stream_rpc_method_handler(
                    servicer.ResourcePostgresShardedV2,
                    request_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedRequestV2.FromString,
                    response_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedResponseV2.SerializeToString,
            ),
            'ResourceRedisSharded': grpc.unary_stream_rpc_method_handler(
                    servicer.ResourceRedisSharded,
                    request_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceRedisShardedRequest.FromString,
                    response_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceRedisShardedResponse.SerializeToString,
            ),
            'ResourceKafka': grpc.unary_unary_rpc_method_handler(
                    servicer.ResourceKafka,
                    request_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceKafkaRequest.FromString,
                    response_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceKafkaResponse.SerializeToString,
            ),
            'ResourceEtcd': grpc.unary_unary_rpc_method_handler(
                    servicer.ResourceEtcd,
                    request_deserializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceEtcdRequest.FromString,
                    response_serializer=platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceEtcdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ozon.platform.warden.api.endpoints.v2.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Application(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/Application',
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ApplicationRequest.SerializeToString,
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ApplicationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResourcePostgres(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourcePostgres',
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresRequest.SerializeToString,
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResourceMSSQL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourceMSSQL',
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceMSSQLRequest.SerializeToString,
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceMSSQLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResourcePostgresSharded(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourcePostgresSharded',
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedRequest.SerializeToString,
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResourcePostgresShardedV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourcePostgresShardedV2',
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedRequestV2.SerializeToString,
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourcePostgresShardedResponseV2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResourceRedisSharded(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourceRedisSharded',
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceRedisShardedRequest.SerializeToString,
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceRedisShardedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResourceKafka(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourceKafka',
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceKafkaRequest.SerializeToString,
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceKafkaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResourceEtcd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ozon.platform.warden.api.endpoints.v2.DiscoveryService/ResourceEtcd',
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceEtcdRequest.SerializeToString,
            platform_dot_warden_dot_api_dot_endpoints_dot_v2_dot_endpoints__pb2.ResourceEtcdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
