# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warden/discovery/v1/discovery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#warden/discovery/v1/discovery.proto\x12%ozon.platform.warden.api.discovery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n\x11NeighboursRequest\x12\x14\n\x07service\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04zone\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07version\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\n\n\x08_serviceB\x07\n\x05_zoneB\n\n\x08_version\"\xf2\x02\n\x12NeighboursResponse\x12U\n\tendpoints\x18\x01 \x03(\x0b\x32\x42.ozon.platform.warden.api.discovery.v1.NeighboursResponse.Endpoint\x12\x10\n\x08versions\x18\x02 \x03(\t\x1a*\n\x08Location\x12\x0c\n\x04zone\x18\x01 \x01(\t\x12\x10\n\x08sub_zone\x18\x02 \x01(\t\x1a\xc6\x01\n\x08\x45ndpoint\x12\x11\n\thost_port\x18\x01 \x01(\t\x12\x10\n\x08pod_name\x18\x02 \x01(\t\x12T\n\x08location\x18\x03 \x01(\x0b\x32\x42.ozon.platform.warden.api.discovery.v1.NeighboursResponse.Location\x12\x10\n\x08is_ready\x18\x04 \x01(\x08\x12\x1c\n\x14\x64\x65\x66\x61ult_route_weight\x18\x05 \x01(\x03\x12\x0f\n\x07version\x18\x06 \x01(\t\"\x11\n\x0fMeshInfoRequest\"A\n\x10MeshInfoResponse\x12\x1c\n\x14\x64\x65\x66\x61ult_route_weight\x18\x01 \x01(\x03\x12\x0f\n\x07version\x18\x02 \x01(\t2\x97\x02\n\x10\x44iscoveryService\x12\x83\x01\n\nNeighbours\x12\x38.ozon.platform.warden.api.discovery.v1.NeighboursRequest\x1a\x39.ozon.platform.warden.api.discovery.v1.NeighboursResponse0\x01\x12}\n\x08MeshInfo\x12\x36.ozon.platform.warden.api.discovery.v1.MeshInfoRequest\x1a\x37.ozon.platform.warden.api.discovery.v1.MeshInfoResponse0\x01\x42KZIgitlab.ozon.ru/platform/warden/client/proto-gen/discovery/v1;discovery_v1b\x06proto3')



_NEIGHBOURSREQUEST = DESCRIPTOR.message_types_by_name['NeighboursRequest']
_NEIGHBOURSRESPONSE = DESCRIPTOR.message_types_by_name['NeighboursResponse']
_NEIGHBOURSRESPONSE_LOCATION = _NEIGHBOURSRESPONSE.nested_types_by_name['Location']
_NEIGHBOURSRESPONSE_ENDPOINT = _NEIGHBOURSRESPONSE.nested_types_by_name['Endpoint']
_MESHINFOREQUEST = DESCRIPTOR.message_types_by_name['MeshInfoRequest']
_MESHINFORESPONSE = DESCRIPTOR.message_types_by_name['MeshInfoResponse']
NeighboursRequest = _reflection.GeneratedProtocolMessageType('NeighboursRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEIGHBOURSREQUEST,
  '__module__' : 'warden.discovery.v1.discovery_pb2'
  # @@protoc_insertion_point(class_scope:ozon.platform.warden.api.discovery.v1.NeighboursRequest)
  })
_sym_db.RegisterMessage(NeighboursRequest)

NeighboursResponse = _reflection.GeneratedProtocolMessageType('NeighboursResponse', (_message.Message,), {

  'Location' : _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
    'DESCRIPTOR' : _NEIGHBOURSRESPONSE_LOCATION,
    '__module__' : 'warden.discovery.v1.discovery_pb2'
    # @@protoc_insertion_point(class_scope:ozon.platform.warden.api.discovery.v1.NeighboursResponse.Location)
    })
  ,

  'Endpoint' : _reflection.GeneratedProtocolMessageType('Endpoint', (_message.Message,), {
    'DESCRIPTOR' : _NEIGHBOURSRESPONSE_ENDPOINT,
    '__module__' : 'warden.discovery.v1.discovery_pb2'
    # @@protoc_insertion_point(class_scope:ozon.platform.warden.api.discovery.v1.NeighboursResponse.Endpoint)
    })
  ,
  'DESCRIPTOR' : _NEIGHBOURSRESPONSE,
  '__module__' : 'warden.discovery.v1.discovery_pb2'
  # @@protoc_insertion_point(class_scope:ozon.platform.warden.api.discovery.v1.NeighboursResponse)
  })
_sym_db.RegisterMessage(NeighboursResponse)
_sym_db.RegisterMessage(NeighboursResponse.Location)
_sym_db.RegisterMessage(NeighboursResponse.Endpoint)

MeshInfoRequest = _reflection.GeneratedProtocolMessageType('MeshInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESHINFOREQUEST,
  '__module__' : 'warden.discovery.v1.discovery_pb2'
  # @@protoc_insertion_point(class_scope:ozon.platform.warden.api.discovery.v1.MeshInfoRequest)
  })
_sym_db.RegisterMessage(MeshInfoRequest)

MeshInfoResponse = _reflection.GeneratedProtocolMessageType('MeshInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESHINFORESPONSE,
  '__module__' : 'warden.discovery.v1.discovery_pb2'
  # @@protoc_insertion_point(class_scope:ozon.platform.warden.api.discovery.v1.MeshInfoResponse)
  })
_sym_db.RegisterMessage(MeshInfoResponse)

_DISCOVERYSERVICE = DESCRIPTOR.services_by_name['DiscoveryService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZIgitlab.ozon.ru/platform/warden/client/proto-gen/discovery/v1;discovery_v1'
  _NEIGHBOURSREQUEST._serialized_start=111
  _NEIGHBOURSREQUEST._serialized_end=226
  _NEIGHBOURSRESPONSE._serialized_start=229
  _NEIGHBOURSRESPONSE._serialized_end=599
  _NEIGHBOURSRESPONSE_LOCATION._serialized_start=356
  _NEIGHBOURSRESPONSE_LOCATION._serialized_end=398
  _NEIGHBOURSRESPONSE_ENDPOINT._serialized_start=401
  _NEIGHBOURSRESPONSE_ENDPOINT._serialized_end=599
  _MESHINFOREQUEST._serialized_start=601
  _MESHINFOREQUEST._serialized_end=618
  _MESHINFORESPONSE._serialized_start=620
  _MESHINFORESPONSE._serialized_end=685
  _DISCOVERYSERVICE._serialized_start=688
  _DISCOVERYSERVICE._serialized_end=967
# @@protoc_insertion_point(module_scope)
