# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

try:  # patched
    from . import bootstrap_pb2 as warden_dot_bootstrap_dot_v1_dot_bootstrap__pb2  # patched
    from .bootstrap_pb2 import *  # patched
except ImportError:  # patched
    from ozbalance.warden.stubs.warden.bootstrap.v1 import bootstrap_pb2 as warden_dot_bootstrap_dot_v1_dot_bootstrap__pb2  # patched
    from ozbalance.warden.stubs.warden.bootstrap.v1.bootstrap_pb2 import *  # patched


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Attributes = channel.unary_unary(
                '/bootstrap.v1.Service/Attributes',
                request_serializer=warden_dot_bootstrap_dot_v1_dot_bootstrap__pb2.AttributesRequest.SerializeToString,
                response_deserializer=warden_dot_bootstrap_dot_v1_dot_bootstrap__pb2.AttributesResponse.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Attributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Attributes': grpc.unary_unary_rpc_method_handler(
                    servicer.Attributes,
                    request_deserializer=warden_dot_bootstrap_dot_v1_dot_bootstrap__pb2.AttributesRequest.FromString,
                    response_serializer=warden_dot_bootstrap_dot_v1_dot_bootstrap__pb2.AttributesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bootstrap.v1.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Attributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bootstrap.v1.Service/Attributes',
            warden_dot_bootstrap_dot_v1_dot_bootstrap__pb2.AttributesRequest.SerializeToString,
            warden_dot_bootstrap_dot_v1_dot_bootstrap__pb2.AttributesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
