"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from abc import (
    ABCMeta,
    abstractmethod,
)

from grpc import (
    Channel,
    Server,
    ServicerContext,
    UnaryUnaryMultiCallable,
)

from ozbalance.warden.stubs.warden.bootstrap.v1.bootstrap_pb2 import (
    AttributesRequest,
    AttributesResponse,
)


class ServiceStub:
    def __init__(self, channel: Channel) -> None: ...
    Attributes: UnaryUnaryMultiCallable[
        AttributesRequest,
        AttributesResponse]


class ServiceServicer(metaclass=ABCMeta):
    @abstractmethod
    def Attributes(self,
        request: AttributesRequest,
        context: ServicerContext,
    ) -> AttributesResponse: ...


def add_ServiceServicer_to_server(servicer: ServiceServicer, server: Server) -> None: ...
