# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warden/bootstrap/v1/bootstrap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ozbalance.warden.stubs.warden.endpoints.v1 import endpoints_pb2 as warden_dot_endpoints_dot_v1_dot_endpoints__pb2  # patched
from ozbalance.warden.stubs.warden.endpoints.v1.endpoints_pb2 import *  # patched


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#warden/bootstrap/v1/bootstrap.proto\x12\x0c\x62ootstrap.v1\x1a#warden/endpoints/v1/endpoints.proto\"8\n\x11\x41ttributesRequest\x12\x10\n\x08pod_name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\"e\n\x12\x41ttributesResponse\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12(\n\x08locality\x18\x03 \x01(\x0b\x32\x16.endpoints.v1.Locality2Z\n\x07Service\x12O\n\nAttributes\x12\x1f.bootstrap.v1.AttributesRequest\x1a .bootstrap.v1.AttributesResponseBLZJgitlab.ozon.ru/platform/warden/bootstrap-gen/pkg/bootstrap/v1;bootstrap_v1b\x06proto3')



_ATTRIBUTESREQUEST = DESCRIPTOR.message_types_by_name['AttributesRequest']
_ATTRIBUTESRESPONSE = DESCRIPTOR.message_types_by_name['AttributesResponse']
AttributesRequest = _reflection.GeneratedProtocolMessageType('AttributesRequest', (_message.Message,), {
  'DESCRIPTOR' : _ATTRIBUTESREQUEST,
  '__module__' : 'warden.bootstrap.v1.bootstrap_pb2'
  # @@protoc_insertion_point(class_scope:bootstrap.v1.AttributesRequest)
  })
_sym_db.RegisterMessage(AttributesRequest)

AttributesResponse = _reflection.GeneratedProtocolMessageType('AttributesResponse', (_message.Message,), {
  'DESCRIPTOR' : _ATTRIBUTESRESPONSE,
  '__module__' : 'warden.bootstrap.v1.bootstrap_pb2'
  # @@protoc_insertion_point(class_scope:bootstrap.v1.AttributesResponse)
  })
_sym_db.RegisterMessage(AttributesResponse)

_SERVICE = DESCRIPTOR.services_by_name['Service']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZJgitlab.ozon.ru/platform/warden/bootstrap-gen/pkg/bootstrap/v1;bootstrap_v1'
  _ATTRIBUTESREQUEST._serialized_start=90
  _ATTRIBUTESREQUEST._serialized_end=146
  _ATTRIBUTESRESPONSE._serialized_start=148
  _ATTRIBUTESRESPONSE._serialized_end=249
  _SERVICE._serialized_start=251
  _SERVICE._serialized_end=341
# @@protoc_insertion_point(module_scope)
