"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from builtins import (
    bool,
    int,
)

from google.protobuf.descriptor import (
    Descriptor,
    FileDescriptor,
)

from google.protobuf.message import (
    Message,
)

from typing import (
    Optional,
    Text,
)

from typing_extensions import (
    Literal,
)

from ozbalance.warden.stubs.warden.endpoints.v1.endpoints_pb2 import (
    Locality,
)


DESCRIPTOR: FileDescriptor


AttributesRequest: AttributesRequest

class AttributesRequest(Message):
    DESCRIPTOR: Descriptor
    POD_NAME_FIELD_NUMBER: int
    NAMESPACE_FIELD_NUMBER: int
    pod_name: Text
    namespace: Text
    def __init__(self,
        *,
        pod_name: Text = ...,
        namespace: Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: Literal["namespace",b"namespace","pod_name",b"pod_name"]) -> None: ...


AttributesResponse: AttributesResponse

class AttributesResponse(Message):
    DESCRIPTOR: Descriptor
    SERVICE_NAME_FIELD_NUMBER: int
    NODE_ID_FIELD_NUMBER: int
    LOCALITY_FIELD_NUMBER: int
    service_name: Text
    node_id: Text
    @property
    def locality(self) -> Locality: ...
    def __init__(self,
        *,
        service_name: Text = ...,
        node_id: Text = ...,
        locality: Optional[Locality] = ...,
        ) -> None: ...
    def HasField(self, field_name: Literal["locality",b"locality"]) -> bool: ...
    def ClearField(self, field_name: Literal["locality",b"locality","node_id",b"node_id","service_name",b"service_name"]) -> None: ...
